site_name: Simple Publishing
author: moso.nate.r@gmail.com
logo: /assets/img/logo-01.png
description: Easily publish markdown and more using GitHub
show_downloads: false

sass:
  sass_dir: _sass
  style: compressed

defaults:
  - scope:
      path: ""         # Empty string = all pages
      type: "pages"    # Only applies to regular pages (not posts)
    values:
      layout: gpt-log
      
incremental: false

theme: jekyll-theme-custom
#remote_theme: pages-themes/midnight

## => GitHub Repository (if the site is hosted by GitHub)
##############################
repository: nater0000/Chats
repository_tree: main


google_analytics: G-J82GR9915G
#google:
#  tag_manager:
#    container_id: G-J82GR9915G

## => Paths
##############################
paths:
  root    : # title link url, "/" (default)
  home    : # home layout url, "/" (default)
  archive : # "/archive.html" (default)
  rss     : # "/feed.xml" (default)

## => Build
##############################
markdown    : kramdown
highlighter : rouge
permalink   : date


## => Post
##############################
## excerpt
excerpt_separator: <!--more-->


## TOC
toc:
  selectors: "h1,h2,h3"
  
  
## => Markdown Enhancements
##############################
## Mathjax
mathjax: # false (default), true
mathjax_autoNumber: # false (default), true

## Mermaid
mermaid: # false (default), true

## Chart
chart: # false (default), true

## => Paginate
##############################
paginate: 8
paginate_path: /page:num # don't change this unless for special need

## => Plugins
##############################
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
  - jekyll-remote-theme
# - jekyll-seo-tag
# - jekyll-feed
#  - jekyll-remote-theme
#  - jekyll-analytics
#  - jekyll-google-tag-manager

# If you have non-gemified Ruby plugins, use plugins_dir instead
#plugins_dir: 
#  - _plugins
  
exclude:
  - CHANGELOG.md
  - HOW_TO_RELEASE.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - markdown-publishing.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor