title: Simple Publishing
author: moso.nate.r@gmail.com
logo: /assets/img/logo-01.png
description: Easily publish markdown and more using GitHub
show_downloads: false

incremental: false

theme: jekyll-theme-midnight
#remote_theme: pages-themes/midnight

google_analytics: G-J82GR9915G
#google:
#  tag_manager:
#    container_id: G-J82GR9915G

plugins:
#  - jekyll-remote-theme
#  - jekyll-analytics
#  - jekyll-google-tag-manager