title: Markdown Publishing
logo: /assets/img/logo-01.png
description: Publish markdown (and more) using GitHub Pages
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
#remote_theme: pages-themes/hacker@v0.2.0
#plugins:
#  - jekyll-remote-theme